### ISSUE TITLE
그린플러그드:서울 [Android]

### ISSUE THREAD

**Issue by windbug99** [windbug99/Greenpluged2019#1]
## 앱구성
- [x] 개별배포 앱 구성
- [x] Find Event 설정
```
인스타: https://www.instagram.com/greenpluggedfestival/
페이스북: https://www.facebook.com/greenplugged
트위터: https://twitter.com/greenplugged
네이버밴드: https://band.us/band/54689448
```
## 메뉴구성
- [x] 홈 `imageContent`
- [x] 공지사항 `notice`
- [x] 아티스트 `infolist`
- [x] F&B `infolist`
- [x] 부스소개 `infolist`
- [x] 구글맵 `googleMap`
- [x] 일정 `schedule`
- [x] 설문조사 `survey`

## 디자인설정
[디자인리소스](https://drive.google.com/drive/folders/1MpLi7N2mw3DGZVQyNVrQXYbaq9qNnGWc)
- [ ] 컬러적용
- [ ] 헤더설정
- [ ] 그외 체크

## 콘텐츠삽입
- [ ] 홈 `imageContent`
- [ ] 공지사항 `notice`
- [ ] 아티스트 `infolist`
- [ ] F&B `infolist`
- [ ] 부스소개 `infolist`
- [ ] 구글맵 `googleMap`
- [ ] 일정 `schedule`
- [ ] 설문조사 `survey`

**Comment by pleasantlife** [comment]
으와아아아앙!

**Comment by pleasantlife** [comment]
> ## 앱구성
> * [x]  개별배포 앱 구성
> * [x]  Find Event 설정
> 
> ```
> 인스타: https://www.instagram.com/greenpluggedfestival/
> 페이스북: https://www.facebook.com/greenplugged
> 트위터: https://twitter.com/greenplugged
> 네이버밴드: https://band.us/band/54689448
> ```
> 
> ## 메뉴구성
> * [x]  홈 `imageContent`
> * [x]  공지사항 `notice`
> * [x]  아티스트 `infolist`
> * [x]  F&B `infolist`
> * [x]  부스소개 `infolist`
> * [x]  구글맵 `googleMap`
> * [x]  일정 `schedule`
> * [x]  설문조사 `survey`
> 
> ## 디자인설정
> [디자인리소스](https://drive.google.com/drive/folders/1MpLi7N2mw3DGZVQyNVrQXYbaq9qNnGWc)
> 
> * [x]  컬러적용
> * [x]  헤더설정
> * [x]  그외 체크
> 
> ## 콘텐츠삽입
> * [x]  홈 `imageContent`
> * [x]  공지사항 `notice`
> * [x]  아티스트 `infolist`
> * [x]  F&B `infolist`
> * [x]  부스소개 `infolist`
> * [x]  구글맵 `googleMap`
> * [x]  일정 `schedule`
> * [x]  설문조사 `survey`

다했어요 쩔죠?

**Comment by windbug99** [comment]
> ## 앱구성
> * [x]  개별배포 앱 구성
> * [x]  Find Event 설정
> 
> ```
> 인스타: https://www.instagram.com/greenpluggedfestival/
> 페이스북: https://www.facebook.com/greenplugged
> 트위터: https://twitter.com/greenplugged
> 네이버밴드: https://band.us/band/54689448
> ```
> 
> ## 메뉴구성
> * [x]  홈 `imageContent`
> * [x]  공지사항 `notice`
> * [x]  아티스트 `infolist`
> * [x]  F&B `infolist`
> * [x]  부스소개 `infolist`
> * [x]  구글맵 `googleMap`
> * [x]  일정 `schedule`
> * [x]  설문조사 `survey`
> 
> ## 디자인설정
> [디자인리소스](https://drive.google.com/drive/folders/1MpLi7N2mw3DGZVQyNVrQXYbaq9qNnGWc)
> 
> * [ ]  컬러적용
> * [ ]  헤더설정
> * [ ]  그외 체크
> 
> ## 콘텐츠삽입
> * [ ]  홈 `imageContent`
> * [ ]  공지사항 `notice`
> * [ ]  아티스트 `infolist`
> * [ ]  F&B `infolist`
> * [ ]  부스소개 `infolist`
> * [ ]  구글맵 `googleMap`
> * [ ]  일정 `schedule`
> * [ ]  설문조사 `survey`
